### ISSUE TITLE
사이트 언어 수정

### ISSUE THREAD

**Issue by marshallku** [lgaeun/lgaeun.github.io#1]
https://github.com/lgaeun/lgaeun.github.io/blob/835ff528a55a49266e6c428fc0332f46937f0d79/_config.yml#L13

`en`에서 `ko`로 수정이 필요해 보입니다.

**Comment by lgaeun** [comment]
그러네요! 감사합니다

**Comment by marshallku** [comment]
[참고](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

```md
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
```

추가로 커밋하실 때 위 키워드 중 하나랑 이슈 넘버 같이 남기시면 이슈도 자동으로 닫히고 이슈와 커밋 간 연동도 되니 다음부터 사용해보시면 편할 거에요.
